version: "3.3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - COMPOSER_VERSION=1
    volumes:
      - ./public_html:/app
      - ./magento.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
      - redis
      - elasticsearch
      - php
    networks:
      - magento2-network
  
  php:
    image: skataria/php-magento2:latest
    container_name: php
    restart: always
    environment:
      - COMPOSER_VERSION=1
      - PHP_DATE_TIMEZONE=GMT
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=4000M
      - PHP_MAX_EXECUTION_TIME=18000
      - PHP_DEBUGGER=xdebug
    ports:
      - "9000:9000"
    volumes:
      - ./public_html:/app
    networks:
      - magento2-network
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=site
    volumes: 
      - ./db:/var/lib/mysql
    networks: 
      - magento2-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - PMA_ABSOLUTE_URI=http://phpmyadmin.test
    ports: 
      - "8080:80"
    links: 
      - mysql:db
    networks: 
      - magento2-network
    depends_on: 
      - mysql

  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    ports: 
      - "6379:6379"
    volumes: 
      - ./redis-cache:/data
    networks: 
      - magento2-network

  elasticsearch:
    image: elasticsearch:7.7.1
    container_name: elasticsearch
    restart: always
    environment: 
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: 
      - 9200:9200
    volumes: 
      - esdata_magento2-network:/usr/share/elasticsearch/data
    networks: 
      - magento2-network

volumes: 
  esdata_magento2-network:
    driver: local
  db:
  redis-cache:

networks: 
  magento2-network:
